name: Taskkill
description: Run sysinternals handle.exe to terminate processes that have files open
author: https://github.com/ca-johnson
requirements:
  - handle64
configuration:
  properties:
    processes:
      type: string
